x-service-templates:
  payment-processor: &payment-processor
    image: zanfranceschi/payment-processor:amd64-20250707101540
    networks:
      - payment-processor
      - payment-processor-db
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"

  payment-processor-db: &payment-processor-db
    image: postgres:17-alpine
    networks:
      - payment-processor-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

services:
  payment-processor-1:
    <<: *payment-processor
    container_name: payment-processor-default
    hostname: payment-processor-default
    environment:
      - TRANSACTION_FEE=0.05
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-default-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8001:8080
    depends_on:
      - payment-processor-db-1
    
  payment-processor-db-1:
    <<: *payment-processor-db
    container_name: payment-processor-default-db
    hostname: payment-processor-default-db

  payment-processor-2:
    <<: *payment-processor
    container_name: payment-processor-fallback
    hostname: payment-processor-fallback
    environment:
      - TRANSACTION_FEE=0.15
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-fallback-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8002:8080
    networks:
      - payment-processor
      - payment-processor-db
    depends_on:
      - payment-processor-db-2
  
  payment-processor-db-2:
    <<: *payment-processor-db
    container_name: payment-processor-fallback-db
    hostname: payment-processor-fallback-db

  # Load Balancer (Envoy)
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: payment-gateway-envoy
    hostname: payment-gateway-envoy
    ports:
      - "9999:10000"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - payment-gateway-1
      - payment-gateway-2
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  # Payment Gateway Instance 1
  payment-gateway-1:
    build:
      context: ./payment-gateway
      dockerfile: Dockerfile
    container_name: payment-gateway-1
    hostname: payment-gateway-1
    environment:
      - PORT=8080
      - PRIMARY_PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080/payments
      - PRIMARY_PAYMENT_PROCESSOR_HEALTH_URL=http://payment-processor-default:8080/payments/service-health
      - FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080/payments
      - FALLBACK_PAYMENT_PROCESSOR_HEALTH_URL=http://payment-processor-fallback:8080/payments/service-health
    depends_on:
      - payment-processor-1
      - payment-processor-2
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "100MB"

  # Payment Gateway Instance 2
  payment-gateway-2:
    build:
      context: ./payment-gateway
      dockerfile: Dockerfile
    container_name: payment-gateway-2
    hostname: payment-gateway-2
    environment:
      - PORT=8080
      - PRIMARY_PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080/payments
      - PRIMARY_PAYMENT_PROCESSOR_HEALTH_URL=http://payment-processor-default:8080/payments/service-health
      - FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080/payments
      - FALLBACK_PAYMENT_PROCESSOR_HEALTH_URL=http://payment-processor-fallback:8080/payments/service-health
    depends_on:
      - payment-processor-1
      - payment-processor-2
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "100MB"
          
networks:
  payment-processor:
    name: payment-processor
    driver: bridge
  payment-processor-db:
    driver: bridge
  payment-gateway-db:
    driver: bridge